#!/bin/bash
export SPARK_MASTER_HOST=spark-master
export SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
export SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
export SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
export SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES}
export SPARK_LOG_DIR=/var/log/spark
export SPARK_CONF_DIR=/opt/spark/conf

export HADOOP_SECURITY_AUTHENTICATION=simple
export HADOOP_SECURITY_AUTHORIZATION=false