apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresPassword | b64enc }}
  readonly-password: {{ .Values.postgresReadOnlyPassword | b64enc }}
  root-password: {{ .Values.postgresRootPassword | b64enc }}