apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE USER '{{ .Values.mysqlReadOnlyUser }}'@'%' IDENTIFIED BY '{{ .Values.mysqlReadOnlyPassword }}';
    GRANT SELECT ON {{ .Values.mysqlDatabase }}.* TO '{{ .Values.mysqlReadOnlyUser }}'@'%';
    FLUSH PRIVILEGES;
