services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ../../.env  # Load global variables
      - .env        # Load MySQL-specific variables
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_READONLY_PASSWORD_FILE: /run/secrets/mysql_readonly_password
    secrets:
      - mysql_root_password
      - mysql_user_password
      - mysql_readonly_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
  mysql_readonly_password:
    file: ./secrets/mysql_readonly_password.txt


volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_MOUNT_LOCATION}
