replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

mysqlRootPassword: "rootpassword"
mysqlUser: "myuser"
mysqlPassword: "mypassword"
mysqlReadOnlyUser: "myreadonlyuser"
mysqlReadOnlyPassword: "readonlypassword"

namespace: bigdata-core
nodeSelector:
  pool: np-storage

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

backup:
  enabled: true
  schedule: "0 3 * * *"
