-- Ensure database exists
CREATE DATABASE IF NOT EXISTS ${POSTGRES_DB};

-- Create read-only user
CREATE USER ${POSTGRES_READONLY_USER} WITH ENCRYPTED PASSWORD '$(cat /run/secrets/postgres_readonly_password)';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READONLY_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_READONLY_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READONLY_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_READONLY_USER};