apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: bigdata-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: "{{ .Values.spark.master.image.repository }}:{{ .Values.spark.master.image.tag }}"
          imagePullPolicy: "{{ .Values.spark.master.image.pullPolicy }}"
          env:
            {{- range $key, $value := .Values.spark.master.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 7077
            - containerPort: 8080
          volumeMounts:
            - name: spark-data
              mountPath: "{{ .Values.volumes.spark-data.mountPath }}"
            - name: spark-logs
              mountPath: "{{ .Values.volumes.spark-logs.mountPath }}"
            - name: delta-storage
              mountPath: "{{ .Values.volumes.delta-storage.mountPath }}"

      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: spark-data-pvc
        - name: spark-logs
          persistentVolumeClaim:
            claimName: spark-logs-pvc
        - name: delta-storage
          persistentVolumeClaim:
            claimName: delta-storage-pvc


