apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  type: ClusterIP
  selector:
    app: spark
    component: worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
